"""add teams and positions

Revision ID: 58ce508e07b9
Revises: 82bdfa47fa2a
Create Date: 2026-10-06 16:22:41.609109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58ce508e07b9'
down_revision: Union[str, Sequence[str], None] = '82bdfa47fa2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'name', name='uq_team_event_name')
    )
    op.create_index(op.f('ix_teams_event_id'), 'teams', ['event_id'], unique=False)
    op.create_index(op.f('ix_teams_org_id'), 'teams', ['org_id'], unique=False)
    op.create_table('positions',
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'name', name='uq_position_team_name')
    )
    op.create_index(op.f('ix_positions_org_id'), 'positions', ['org_id'], unique=False)
    op.create_index(op.f('ix_positions_team_id'), 'positions', ['team_id'], unique=False)
    op.add_column('shifts', sa.Column('position_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_shifts_position_id'), 'shifts', ['position_id'], unique=False)
    op.create_foreign_key(
        'fk_shifts_position_id_positions', 'shifts', 'positions', ['position_id'], ['id']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_shifts_position_id_positions', 'shifts', type_='foreignkey')
    op.drop_index(op.f('ix_shifts_position_id'), table_name='shifts')
    op.drop_column('shifts', 'position_id')
    op.drop_index(op.f('ix_positions_team_id'), table_name='positions')
    op.drop_index(op.f('ix_positions_org_id'), table_name='positions')
    op.drop_table('positions')
    op.drop_index(op.f('ix_teams_org_id'), table_name='teams')
    op.drop_index(op.f('ix_teams_event_id'), table_name='teams')
    op.drop_table('teams')
    # ### end Alembic commands ###
