"""add signup response token

Revision ID: f2f4a1748bae
Revises: a9a482fef541
Create Date: 2026-10-09 04:34:30.433579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2f4a1748bae'
down_revision: Union[str, Sequence[str], None] = 'a9a482fef541'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('signups', sa.Column('response_token_hash', sa.String(length=64), nullable=True))
    op.create_unique_constraint(
        'uq_signups_response_token_hash', 'signups', ['response_token_hash']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_signups_response_token_hash', 'signups', type_='unique')
    op.drop_column('signups', 'response_token_hash')
    # ### end Alembic commands ###
